Description: DynamoDB IAM Policy
Parameters:
  Namespace:
    Description: The namespace which this table belongs to
    Type: String
    Default: development
Resources:
  IamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - dynamodb:BatchGetItem
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:UpdateItem
          Resource: "*"
      ManagedPolicyName: !Sub "${Namespace}-dynamodb-policy"
Outputs:
  IamPolicyArn:
    Value: !Ref IamPolicy