apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: app-s3-iam-service-account
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 80
